apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl_checker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssl_checker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
      {{- include "ssl_checker.selectorLabels" . | nindent 4 }}
