apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ssl-expiry-prometheus-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
     {{- include "ssl-expiry-prometheus-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ssl-expiry-prometheus-operator.selectorLabels" . | nindent 5 }}
  endpoints:
  - targetPort: metrics
    port: metrics
    path: /metrics
    scrapeTimeout: 60s
    interval: 120s