apiVersion: v1
entries:
  k8s-ingress-ssl-metrics-exporter:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-04-25T11:04:49.199519+05:30"
    description: Prometheus Exporter that checks the SSL certificates of all ingress
      hosts within all namespaces.
    digest: 81e5f218871555b9586b415aa2c59dda95ede647f253ae5d38edeb7a01bca316
    name: k8s-ingress-ssl-metrics-exporter
    type: application
    urls:
    - k8s-ingress-ssl-metrics-exporter-1.0.0.tgz
    version: 1.0.0
generated: "2023-04-25T11:04:49.199061+05:30"
